Updated Registration details
bioinformatics-hub-ke/BOSS22 pull request #54
Opened 2022-03-16 14:23 UTC by karegapauline

2022-03-16 14:34 UTC, bkmgit commented on pages/en/register.markdown
> +- Registration open: 10th March 2022
```suggestion
- Registration open: 16th March 2022
```

2022-03-16 14:34 UTC, bkmgit commented on pages/en/register.markdown
> +Submissions are done in Open Review. Follow this link: [Register Here](https://openreview.net/group?id=bioinformatics-hub-ke.github.io/BOSS/2022/Conference)
```suggestion
Submissions are done in Open Review, [submit here](https://openreview.net/group?id=bioinformatics-hub-ke.github.io/BOSS/2022/Conference).
```

2022-03-16 14:55 UTC, karegapauline commented on pages/en/register.markdown
> +Visit our wiki pages for Abstract submission guidelines
They are quite a lot of details in the guide

2022-03-16 15:07 UTC, bkmgit commented on pages/en/register.markdown
> +Visit our wiki pages for Abstract submission guidelines
Then perhaps add a link to the wiki? Expect that viewing on the webpage is nice than the wiki.

2022-03-16 15:08 UTC, bkmgit commented on pages/en/register.markdown
> +Visit our wiki pages for Abstract submission guidelines
However, this should not be a point of contention.

2022-03-16 15:08 UTC, bkmgit commented on pages/en/register.markdown
> +Visit our wiki pages for Abstract submission guidelines
Let me know when ready for another review.

2022-03-16 15:09 UTC, kipkurui requested changes
@karegapauline, let's add the guide at the end

2022-03-16 15:09 UTC, kipkurui commented on pages/en/register.markdown
> +Visit our wiki pages for Abstract submission guidelines
I think we can just add them at the end of the Call for Abstracts

2022-03-17 13:07 UTC, kipkurui commented on pages/en/register.markdown
> +Visit our wiki pages for Abstract submission guidelines
I agree, we can merge as is then can update later.

2022-03-17 13:07 UTC, kipkurui approved these changes

2022-03-17 13:07 UTC, merged